name: Build and Deploy to ACK

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow.
env:
  REGION_ID: cn-chengdu
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: wizz-project
  IMAGE: orientation-system-be
  # TAG: ${{ github.sha }}
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 1.1 Login to ACR
      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: 'registry.cn-chengdu.aliyuncs.com' # default: https://index.docker.io/v1/
          username: 'xdwizz'
          password: 'hfDGoKMpVuv9Up'
          
          # region-id: "${{ env.REGION_ID }}"
          # access-key-id: "LTAI5tPrM5s6tYg3p7XfLDUR"
          # access-key-secret: "9WqpADbgGB8KKkbn6CbrgZQoV3xT0X"

      # 1.2 Buid and push image to ACR
      - name: Build and push image to ACR
        run: |
          docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .  
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"

      # 1.3 Scan image in ACR
      - name: Scan image in ACR
        uses: aliyun/acr-scan@v1
        with:
          region-id: "${{ env.REGION_ID }}"
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
          repository: "${{ env.NAMESPACE }}/${{ env.IMAGE }}"
          tag: "${{ env.TAG }}"
